id: P007857
initial_creation_type: ocr
source_metadata:
  id: bdr:W20829
  title: ཞྭ་སྒབ་པའི་བོད་ཀྱི་སྲིད་དོན་རྒྱལ་རབས་དང་བོད་ཀྱི་ལོ་རྒྱུས་དངོས།
  author: ''
  volumes:
    1f8dd86214604f1a879b79597178777c:
      image_group_id: I1KG24081
      title: ''
      volume_number: 1
      total_pages: 302
ebook_metadata:
  title: ཞྭ་སྒབ་པའི་བོད་ཀྱི་སྲིད་དོན་རྒྱལ་རབས་དང་བོད་ཀྱི་ལོ་རྒྱུས་དངོས།
  author: ''
  sku: P007857
  cover: cover.jpg
  layers:
  - pagination
