id: I130CDC6B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T22:44:00+00:00'
last_modified: '2022-06-09T06:40:14.646591+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W20829
  title: ཞྭ་སྒབ་པའི་བོད་ཀྱི་སྲིད་དོན་རྒྱལ་རབས་དང་བོད་ཀྱི་ལོ་རྒྱུས་དངོས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '8254':
      image_group_id: I1KG24081
      title: Volume 1 of zhwa sgab pa'i bod kyi srid don rgyal rabs dang bod kyi lo
        rgyus dngos/
      total_pages: 302
      order: 1
      base_file: 8254.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
